# Generated by Django 6.1 on 2026-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_status_payment_stripe_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID сессии в Stripe'),
        ),
    ]
